name: layrz_csvwriter
description: Lightweight, cross-platform Dart package to write CSV data to a `StringSink`. Supports and extends RFC 4180.
version: 1.0.1
repository: https://github.com/goldenm-software/layrz_csvwriter

environment:
  sdk: ">=3.9.0 <4.0.0"

# dependencies:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
